Project3/force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Project3/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Fill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project3/force-app/main/default/classes/CreateOrderBatch.cls
global class CreateOrderBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id FROM Contact';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Contact> contactsList){
        List<Order__c> ordersList = new List<Order__c>(); 
        
        for (Contact contact :contactsList) {
            for (Integer i=0 ;i <10;i++) {
                ordersList.add(new Order__c(Contact__c = contact.Id, Status__c = 'Draft')); 
            }
        }
        insert ordersList; 
    }
    
    global void finish(Database.BatchableContext bc){ 
    }  
}