Project3/force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Skill_Assignment__c/Skill_Assignment__c.object-meta.xml
<CustomObject>
    <label>Skill Assignment</label>
    <nameField>
        <label>Skill Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SkillAssignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Skill_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SkillAssignments</relationshipLabel>
    <relationshipName>SkillAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Skill_Assignment__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project3/force-app/main/default/objects/Skill_Assignment__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>SkillAssignments</relationshipLabel>
    <relationshipName>SkillAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/classes/SOQL.cls
public class SOQL {
 // All contacts who know English at least Medium level(use operator In here)
 //SELECT Contact__r.Name, Skill_Assignment__c.Level__c, Skill__r.Name FROM Skill_Assignment__c Where Skill_Assignment__c.Level__c not in ('Low', 'Medium') AND Skill__r.Name ='English' AND Skill_Assignment__c.Level__c !=null

  //Departments with average salary less than 450
  //SELECT Department__r.Name, FORMAT(Avg(Salary__c)) FROM Contact GROUP BY Department__r.Name HAVING Avg(Salary__c)>450
  
  //Department with the highest average salary
  //SELECT Department__r.Name, FORMAT(Avg(Salary__c)) FROM Contact GROUP BY Department__r.Name HAVING Avg(Salary__c)!=null ORDER BY Avg(Salary__c) DESC LIMIT 1
  
  //All contacts who have First Name starting with ‘A’ character
  //SELECT FirstName FROM Contact WHERE FirstName LIKE 'A%'
  
  //Three most popular skills
  //SELECT  Skill__r.Name, COUNT(Id) FROM Skill_Assignment__c GROUP BY Skill__r.Name ORDER BY COUNT(Id) DESC LIMIT 3


}